### ISSUE TITLE
Como traduzir "Dangling References"

### ISSUE THREAD

**Issue by marimeireles** [rust-br/glossario#1]
Pensei nas seguintes alternativas (por ordem de preferência):

-referências expiradas
-soltas
-inválidas
-vencidas

Acredito que expiradas engloba mais o sentido da expressão. Acho que inválidas seja impreciso e soltas mais vago que expirado. Mas, não estou segura sobre se expiradas é uma boa.
Alguém tem alguma sugestão?

Valeu.

**Comment by hsribei** [comment]
No StackOverflow em Português vejo o pessoal usando "dangling pointer" mesmo, não encontrei uma tradução. Talvez seja o caso de traduzir na primeira ocorrência e continuar usando em inglês.

Entre as traduções dadas pela [Wikipédia](https://pt.wikipedia.org/wiki/Apontador_pendente), "solto" parece o mais próximo de "dangling" e o que soa melhor IMO.

**Comment by marimeireles** [comment]
Obrigada pelo ótimo feedback. :)
Vou usar soltas mesmo.
